#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <time.h>
#include <errno.h>
#include <dirent.h>
#include <sys/types.h>
#include <signal.h>
#include <sys/time.h>
#include <sys/select.h>
#include <unistd.h>
#include <execinfo.h>
#include <assert.h>
#include <poll.h>
#include <netinet/in_systm.h>
#include <netinet/ip.h>
#include <netdb.h>
#include <netinet/ip_icmp.h>
#include <netinet/ip.h>
#include <netinet/tcp.h>
#include <netinet/udp.h>
#include <math.h>
#include <termios.h>

#include "socket_mods.h"
#include "udp_header.h"
#include "socket_headers.h"
extern int sigNum;